# Site-wide settings
# ------------------
title: Init Venv - PyPI

author:
  name: Dev2Forge
  email: support@dev2forge.software

url: "https://www.dev2forge.software"
baseurl: "/initvenv"

# disqus:
#   shortname: init-venv

# Analytics
# google_analytics: "G-74L9F7VNLD"
google_analytics: "G-5DQRS8Q87X"

description: >-
  Cross-language CLI tool written in C# to initialize Python virtual
  environments instantly with one command: 'initvenv'. Open Source - GPL-3.0

# Build settings
# --------------
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

# Minima-specific settings (solo aplica si usas minima >= 3 localmente)
minima:
  skin: auto

  nav_pages:
    - index.md
    - view/download.md
    - view/howuse.md
    - view/screenshots.md
    - about.md

  social_links:
    - title: Init Venv - PyPI Version
      icon: github
      url: "https://github.com/Dev2Forge/initvenv/"

    - title: Init Venv - Native Version
      icon: github
      url: "https://github.com/Dev2Forge/Init-Venv/"

    - title: Init Venv - PyPI Version
      icon: python
      url: "https://pypi.org/project/initvenv/"

# Project Variables (puedes usarlas en tus layouts y includes)
PROJECT_NAME: "Init Venv"
AUTHOR: "Tutos Rive"
FAVICON: "/assets/initvenv.ico"
