# Configs
theme: minima

title: Init Venv - Initialize Python Virtual Environments

author:
  name: Dev2Forge
  email: support@dev2forge.software

description: >
  Cross-language CLI tool written in C# to initialize Python virtual
  environments instantly with one command: 'initvenv'. Open Source - GPL-3.0


# Project Variables
url: "hhttps://www.dev2forge.software"
baseurl: "/initvenv"
PROJECT_NAME: "Init Venv"
AUTHOR: "Tutos Rive"
FAVICON: "/assets/initvenv.ico"

# Analitycs
google_analytics: "G-74L9F7VNLD"

# Components variables
ALT_PROFILE_TRG: "Github Phot Profile of Tutos Rive"
IMG_PROFILE: "/assets/me1.jpeg"

plugins:
 - jekyll-feed
 - jekyll-seo-tag

minima:
  skin: dark

social_links:
    - title: Init Venv - Pypi Version
      icon: github
      url: "https://github.com/Dev2Forge/initvenv/"

    - title: Init Venv - Native Version
      icon: github
      url: "https://github.com/Dev2Forge/Init-Venv/"

    - title: Init Venv - Pypi Version
      icon: python
      url: "https://pypi.org/project/initvenv/"